### ISSUE TITLE
Support for fastify v3?

### ISSUE THREAD

**Issue by wesselvdv** [ericrglass/fastify-normalize-request-reply#3]
Any idea if this will be upgraded to work with fastify v3?

**Comment by ericrglass** [comment]
I will take a look this weekend to see what is involved.

**Comment by ericrglass** [comment]
Have updated the Fastify dependency to 3.x, ran the test successfully, and published to npm.

**Comment by ericrglass** [comment]
Sorry, I was premature in my testing. Unpublished and still modifying more for the newer version of Fastify 3.x

**Comment by ericrglass** [comment]
Sorry, attempts where made to see if this code could be updated to Fastify 3.x, but because of the way Fastify was changed in the way it handles middleware now it is impossible to do.
